# Generated by Django 4.2 on 2025-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('B', 'Fuego'), ('A', 'Agua'), ('E', 'Electrico'), ('D', 'Planta'), ('C', 'Tierra'), ('F', 'Lagartija')], max_length=30),
        ),
    ]
