# Generated by Django 4.2 on 2025-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(null=True, upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('D', 'Planta'), ('A', 'Agua'), ('E', 'Electrico'), ('F', 'Lagartija'), ('C', 'Tierra'), ('B', 'Fuego')], max_length=30),
        ),
    ]
